### ISSUE TITLE
tiny_msgs/tinyVector.h: No such file or directory  #include <tiny_msgs/tinyVector.h>

### ISSUE THREAD

**Issue by ManChrys** [superjax/tinyIMU_arduino#6]
Hello

the file tinyVector.h doesnt exist in the folder after cmake. Probably deleted?

EDIT

I cant find any file with .h extend in the whole package

**Comment by superjax** [comment]
See #5

The ros message definitions are generated by catkin.

**Comment by ManChrys** [comment]
ok i fixed it ty.
